FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .
COPY start.sh .

RUN chmod +x start.sh

EXPOSE 5000

CMD ["./start.sh"]

