apiVersion: v1
kind: Pod
metadata:
  name: kuard-resources
  namespace: victor-leopold
spec:
  containers:
    - name: kuard
      image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      resources:
        requests:
          cpu: "50m"
          memory: "128Mi"
        limits:
          cpu: "50m"
          memory: "128Mi"
