apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  namespace: victor-leopold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lele9627/calculatrice-backend:v1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "4m"
              memory: "32Mi"

