apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: victor-leopold
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: lele9627/calculatrice-consumer:v1
          env:
            - name: REDIS_HOST
              value: redis-service
            - name: REDIS_PORT
              value: "6379"
            - name: RABBIT_HOST
              value: rabbitmq-service
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_QUEUE
              value: calc_jobs

